name: cobertura

on: [push]
  

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.9
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
        - name: Codacy Coverage Reporter
          uses: codacy/codacy-coverage-reporter-action@v1
          with:
              project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
              coverage-reports: decide/coverage.xml